<?php

declare(strict_types=1);

namespace App\MoonShine\Pages;

use App\Enums\TaskStatus;
use App\Models\Task;
use App\MoonShine\Components\KanbanBoard;
use App\MoonShine\Components\KanbanColumn;
use App\MoonShine\Components\TaskCardsBuilder;
use App\MoonShine\Resources\Task\Pages\TaskFormPage;
use App\MoonShine\Resources\Task\TaskResource;
use MoonShine\Laravel\Pages\Page;
use MoonShine\Contracts\UI\ComponentContract;
use MoonShine\Support\Attributes\Icon;
use MoonShine\UI\Components\ActionButton;
use MoonShine\UI\Components\Layout\Box;
use MoonShine\UI\Components\Modal;

#[Icon('clipboard-document-list')]
class Kanban extends Page
{
    public function getBreadcrumbs(): array
    {
        return ['#' => $this->getTitle()];
    }

    public function getTitle(): string
    {
        return $this->title ?: 'Доска';
    }


    protected function components(): iterable
    {
        return [
            ...$this->topLayer(),
            ...$this->mainLayer(),
            ...$this->bottomLayer()
        ];
    }

    protected function topLayer(): array
    {
        return [
            Box::make([
                ActionButton::make('Создать задачу')
                    ->primary()
                    ->inModal(
                        title: 'Modal Window Title',
                        content: 'Modal Window Content',
                        name: 'new-task',
                    ),
            ]),
        ];
    }

    protected function mainLayer(): array
    {
        $tasksByStatus = Task::query()
            ->with(['assignee', 'tags'])
            ->orderBy('id')
            ->get()
            ->groupBy(fn(Task $task) => $task->status->value);

        $columns = array_map(function (TaskStatus $status) use ($tasksByStatus): KanbanColumn {
            $tasks = $tasksByStatus->get($status->value, collect());

            $cards = TaskCardsBuilder::make($tasks)
                ->url(fn(Task $task) => toPage(
                    page: TaskFormPage::class,
                    resource: TaskResource::class,
                    params: ['resourceItem' => $task->id],
                ));

            return KanbanColumn::make(
                labelOrComponents: "{$status->label()} ({$tasks->count()})",
                components: [$cards],
            );
        }, TaskStatus::cases());

        return [
            KanbanBoard::make($columns),
        ];
    }

    protected function bottomLayer(): array
    {
        return parent::bottomLayer(); // TODO: Change the autogenerated stub
    }
}
